$(function(){
	var url = "http://localhost/medicion/";
	$("#inicio").click(function(){	    
	    location.href=url+"home.php"; 
	 });
	$("#paneladm").click(function(){	    
	    location.href=url+"PanelAdmin/"; 
	 });
	$("#cotizacion").click(function(){	    
	    location.href=url+"Cotizacion/index.php"; 
	 });
	$("#inventario").click(function(){	    
	    location.href=url+"inventario/index.php?pagina=1"; 
	 });
	$("#verobra").click(function(){	    
	    location.href=url+"Obra/ver_obra.php?pagina=1"; 
	 });
	$("#newobra").click(function(){	    
	    location.href=url+"Obra/nueva_obra.php"; 
	 });
	$("#verproveedores").click(function(){	    
	    location.href=url+"proveedores/index.php?pagina=1"; 
	 });
	$("#newproveedores").click(function(){	    
	    location.href=url+"Proveedores/nuevo_proveedor.php"; 
	 });
	$("#verdirectorio").click(function(){	    
	    location.href=url+"Directorio/index.php?pagina=1"; 
	 });
});