<?php
header('Content-type: text/html; charset=utf-8');
session_start();
unset($_SESSION["usuario"]); 
unset($_SESSION["password"]); 
unset($_SESSION["id"]); 
unset($_SESSION["codigo"]); 
unset($_SESSION["nombre"]);
unset($_SESSION["idproducto"]);
unset($_SESSION["codigo"]);
unset($_SESSION["descripcion"]);
unset($_SESSION["precioventa"]);
unset($_SESSION["cantidad"]);
unset($_SESSION["total"]);
unset($_SESSION["caN"]);
unset($_SESSION["totalgeneral"]);
unset($_SESSION["factura"]);
unset($_SESSION["cliente"]);
unset($_SESSION["nit"]);
unset($_SESSION["clienteid"]);
unset($_SESSION["clientenombre"]);
unset($_SESSION["fedido"]);
unset($_SESSION["hpedido"]);
unset($_SESSION["nroenvio"]);
unset($_SESSION["nromovil"]);
unset($_SESSION["dedicatoria"]);
unset($_SESSION["obspedido"]);
session_destroy();
?>